In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
#Loading the dataset
from sklearn.datasets import load_iris
iris = load_iris()

## Separating X & Y and Splitting the train & test

In [0]:
#Separating X & y
X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=1)

## Naive Bayes

In [0]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred_nb = gnb.predict(X_test)

from sklearn import metrics
print('Gaussian Naive Bayes model accuracy(in%):', metrics.accuracy_score(y_test, y_pred_nb)*100)
class_names = iris.target_names
print(class_names)

print('Confusion Matrix   the Gaussioan Naive Bayes Classfier', metrics.confusion_matrix(y_test, y_pred_nb))

Gaussian Naive Bayes model accuracy(in%): 93.33333333333333
['setosa' 'versicolor' 'virginica']
Confusion Matrix   the Gaussioan Naive Bayes Classfier [[14  0  0]
 [ 0 16  2]
 [ 0  1 12]]


## K Nearest Neighbor

In [0]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
y_pred_knn = neigh.predict(X_test)

from sklearn import metrics
print('KNN model accuracy(in%):', metrics.accuracy_score(y_test, y_pred_knn)*100)
class_names = iris.target_names
print(class_names)
print('Confusion Matrix the KNN Classfier', metrics.confusion_matrix(y_test, y_pred_knn))


KNN model accuracy(in%): 97.77777777777777
['setosa' 'versicolor' 'virginica']
Confusion Matrix the KNN Classfier [[14  0  0]
 [ 0 18  0]
 [ 0  1 12]]


## Decision Tree

In [0]:
#Applying Decision Tree
from sklearn import tree
#Create tree object
decision_tree = tree.DecisionTreeClassifier(criterion='gini')
#Train DT based on scaled training set
decision_tree.fit(X_train, y_train)
y_pred_dt = decision_tree.predict(X_test)

from sklearn import metrics
print('Decision Tree model accuracy(in%):', metrics.accuracy_score(y_test, y_pred_dt)*100)
class_names = iris.target_names
print(class_names)
print('Confusion Matrix the DT Classfier', metrics.confusion_matrix(y_test, y_pred_dt))

Decision Tree model accuracy(in%): 95.55555555555556
['setosa' 'versicolor' 'virginica']
Confusion Matrix the DT Classfier [[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


## Random Forest

In [0]:
#Applying RandomForest
from sklearn.ensemble import RandomForestClassifier
#Create Random Forest object
random_forest = RandomForestClassifier()
#Train model
random_forest.fit(X_train, y_train)
y_pred_rf = random_forest.predict(X_test)

from sklearn import metrics
print('Random Forest model accuracy(in%):', metrics.accuracy_score(y_test, y_pred_rf)*100)
class_names = iris.target_names
print(class_names)
print('Confusion Matrix the RF Classfier', metrics.confusion_matrix(y_test, y_pred_rf))

Random Forest model accuracy(in%): 95.55555555555556
['setosa' 'versicolor' 'virginica']
Confusion Matrix the RF Classfier [[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


##Support Vector Classifier

In [0]:
#Applying SVC (Support Vector Classification)
from sklearn.svm import SVC

svm = SVC(kernel='rbf', random_state=0, gamma=.10, C=1.0)
svm.fit(X_train, y_train)
y_pred_svc = svm.predict(X_test)

from sklearn import metrics
print('SVC  model accuracy(in%):', metrics.accuracy_score(y_test, y_pred_svc)*100)
class_names = iris.target_names
print(class_names)
print('Confusion Matrix the SVC Classfier', metrics.confusion_matrix(y_test, y_pred_svc))

SVC  model accuracy(in%): 97.77777777777777
['setosa' 'versicolor' 'virginica']
Confusion Matrix the SVC Classfier [[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]


## XG Boost

In [0]:
import xgboost as xgb
xgb_clf = xgb.XGBClassifier()
xgb_clf = xgb_clf.fit(X_train, y_train)
y_pred_xgb = xgb_clf.predict(X_test)

from sklearn import metrics
print('XG_Boost  model accuracy(in%):', metrics.accuracy_score(y_test, y_pred_xgb)*100)
class_names = iris.target_names
print(class_names)
print('Confusion Matrix the XGB Classfier', metrics.confusion_matrix(y_test, y_pred_xgb))

XG_Boost  model accuracy(in%): 95.55555555555556
['setosa' 'versicolor' 'virginica']
Confusion Matrix the XGB Classfier [[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


# Conclusion 
This notebook explored 6 basic machine learning algorithms. In the majority of them, the accuracy was higher in the training dataset, as expected. In the ones it was lower, the difference in not significant. The accuracy for those cases should be evaluated with a cross validation and not only with a single fold. Using cross validation will probably result in higher accuracy for all algorithms. This dataset is very simple, so maybe we cannot note significant improvement in the algorithms.